git_name: git
vim_name: vim

# all tools that need to be installed via git can be added here
git_urls:
  Sublist3r:
    repo: https://github.com/aboul3la/Sublist3r.git
    dest: /opt/sublist3r
  dirsearch:
    repo: https://github.com/maurosoria/dirsearch.git
    dest: /opt/dirsearch