---
- name: "Pyenv - for multiple Python interpreters"
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"

- name: "Update bashrc"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item.line }}"
    regexp: "{{ item.re }}"
  with_items:
    - line: 'export PYENV_ROOT="$HOME/.pyenv"'
      re: 'PYENV_ROOT='
    - line: 'export PATH="$PYENV_ROOT/bin:$PATH"'
      re: 'PYENV_ROOT/bin'
    - line: 'eval "$(pyenv init -)"'
      re: 'pyenv init'
